@if (auth()->user()->is_root || auth()->user()->is_admin || auth()->user()->is_procesos || auth()->user()->is_ps_diamond)
    <a href="" data-codigocliente="{{ $codigoCliente }}" data-nombre="{{ $nombre }}" data-apellidop="{{ $apellido_p }}" data-apellidom="{{ $apellido_m }}" data-fechanac="{{ $fecha_nac }}" data-nacionalidad="{{ $nacionalidad }}" data-direccion="{{ $direccion }}" data-colonia="{{ $colonia }}" data-cp="{{ $cp }}" data-ciudad="{{ $ciudad }}" data-estado="{{ $estado }}" data-celular="{{ $celular }}" data-correop="{{ $correo_personal }}" data-correoi="{{ $correo_institucional }}" data-ine="{{ $ine }}" data-pasaporte="{{ $pasaporte }}" data-vencimientopas="{{ $vencimiento_pasaporte }}" data-swift="{{ $swift }}" data-iban="{{ $iban }}" data-inedocumento="{{ $ine_documento }}" data-pasaportedocumento="{{ $pasaporte_documento }}" data-comprobantedomicilio="{{ $comprobante_domicilio }}" data-lpoadocumento="{{ $lpoa_documento }}" data-formapertura="{{ $formulario_apertura }}" data-formriesgos="{{ $formulario_riesgos }}" data-tarjeta="{{ $tarjeta }}" data-identificador="{{ $identificador_mam }}" type="button" title="Vista previa" class="btn btn-primary btn-sm btn-icon view"> <i class="bi bi-eye"></i></a>
    <a href="" data-id="{{ $id }}" data-codigocliente="{{ $codigoCliente }}" data-nombre="{{ $nombre }}" data-apellidop="{{ $apellido_p }}" data-apellidom="{{ $apellido_m }}" data-fechanac="{{ $fecha_nac }}" data-nacionalidad="{{ $nacionalidad }}" data-direccion="{{ $direccion }}" data-colonia="{{ $colonia }}" data-cp="{{ $cp }}" data-ciudad="{{ $ciudad }}" data-estado="{{ $estado }}" data-celular="{{ $celular }}" data-correop="{{ $correo_personal }}" data-correoi="{{ $correo_institucional }}" data-ine="{{ $ine }}" data-pasaporte="{{ $pasaporte }}" data-vencimientopas="{{ $vencimiento_pasaporte }}" data-swift="{{ $swift }}" data-iban="{{ $iban }}" data-inedocumento="{{ $ine_documento }}" data-pasaportedocumento="{{ $pasaporte_documento }}" data-comprobantedomicilio="{{ $comprobante_domicilio }}" data-lpoadocumento="{{ $lpoa_documento }}" data-formapertura="{{ $formulario_apertura }}" data-formriesgos="{{ $formulario_riesgos }}" data-tarjeta="{{ $tarjeta }}" data-identificador="{{ $identificador_mam }}" type="button" title="Editar cliente" class="btn btn-success btn-sm btn-icon edit" id="edit"> <i class="bi bi-pencil"></i></a>
    <a href="" data-id="{{ $id }}" type="button" title="Eliminar cliente" class="btn btn-danger btn-sm btn-icon delete"> <i class="bi bi-trash"></i></a>
    {{-- <a href="" data-id="{{ $id }}" data-nombre="{{ $nombre }}" data-apellidop="{{ $apellido_p }}" data-apellidom="{{ $apellido_m }}" data-numero="{{ $celular }}" type="button" title="Mandar whats" class="btn btn-success btn-sm btn-icon whats"> <i class="bi bi-whatsapp"></i></a> --}}
    <a href="" data-id="{{ $id }}" data-nombre="{{ $nombre }}" data-apellidop="{{ $apellido_p }}" data-apellidom="{{ $apellido_m }}" data-fechanac="{{ $fecha_nac }}" type="button" title="Imprimir LPOA" class="imprimirLPOAButton btn btn-dark btn-sm btn-icon print d-none"> <i class="bi bi-file-earmark-pdf-fill"></i></a>
    <button title="Comprobante de pago" class="btn @if ($comprobante_mam_img == null) btn-dark @else btn-secondary @endif btn-sm btn-icon nota d-none" data-id="{{ $id }}" data-codigo="{{$codigoCliente}}" data-comprobanteimg="{{$comprobante_mam_img}}" data-comprobantenota="{{$comprobante_mam_nota}}"> <i class="bi bi-journal-text"></i></button>
@elseif (auth()->user()->is_egresos)
    <a href="" data-codigocliente="{{ $codigoCliente }}" data-nombre="{{ $nombre }}" data-apellidop="{{ $apellido_p }}" data-apellidom="{{ $apellido_m }}" data-fechanac="{{ $fecha_nac }}" data-nacionalidad="{{ $nacionalidad }}" data-direccion="{{ $direccion }}" data-colonia="{{ $colonia }}" data-cp="{{ $cp }}" data-ciudad="{{ $ciudad }}" data-estado="{{ $estado }}" data-celular="{{ $celular }}" data-correop="{{ $correo_personal }}" data-correoi="{{ $correo_institucional }}" data-ine="{{ $ine }}" data-pasaporte="{{ $pasaporte }}" data-vencimientopas="{{ $vencimiento_pasaporte }}" data-swift="{{ $swift }}" data-iban="{{ $iban }}" data-inedocumento="{{ $ine_documento }}" data-pasaportedocumento="{{ $pasaporte_documento }}" data-comprobantedomicilio="{{ $comprobante_domicilio }}" data-lpoadocumento="{{ $lpoa_documento }}" data-formapertura="{{ $formulario_apertura }}" data-formriesgos="{{ $formulario_riesgos }}" data-tarjeta="{{ $tarjeta }}" data-identificador="{{ $identificador_mam }}" type="button" title="Vista previa" class="btn btn-primary btn-sm btn-icon view"> <i class="bi bi-eye"></i> Ver cliente</a>
@elseif (auth()->user()->is_ps_bronze)
    <a href="" data-codigocliente="{{ $codigoCliente }}" data-nombre="{{ $nombre }}" data-apellidop="{{ $apellido_p }}" data-apellidom="{{ $apellido_m }}" data-fechanac="{{ $fecha_nac }}" data-nacionalidad="{{ $nacionalidad }}" data-direccion="{{ $direccion }}" data-colonia="{{ $colonia }}" data-cp="{{ $cp }}" data-ciudad="{{ $ciudad }}" data-estado="{{ $estado }}" data-celular="{{ $celular }}" data-correop="{{ $correo_personal }}" data-correoi="{{ $correo_institucional }}" data-ine="{{ $ine }}" data-pasaporte="{{ $pasaporte }}" data-vencimientopas="{{ $vencimiento_pasaporte }}" data-swift="{{ $swift }}" data-iban="{{ $iban }}" data-inedocumento="{{ $ine_documento }}" data-pasaportedocumento="{{ $pasaporte_documento }}" data-comprobantedomicilio="{{ $comprobante_domicilio }}" data-lpoadocumento="{{ $lpoa_documento }}" data-formapertura="{{ $formulario_apertura }}" data-formriesgos="{{ $formulario_riesgos }}" data-tarjeta="{{ $tarjeta }}" data-identificador="{{ $identificador_mam }}" type="button" title="Vista previa" class="btn btn-primary btn-sm btn-icon view"> <i class="bi bi-eye"></i></a>
    <a href="" data-id="{{ $id }}" data-codigocliente="{{ $codigoCliente }}" data-nombre="{{ $nombre }}" data-apellidop="{{ $apellido_p }}" data-apellidom="{{ $apellido_m }}" data-fechanac="{{ $fecha_nac }}" data-nacionalidad="{{ $nacionalidad }}" data-direccion="{{ $direccion }}" data-colonia="{{ $colonia }}" data-cp="{{ $cp }}" data-ciudad="{{ $ciudad }}" data-estado="{{ $estado }}" data-celular="{{ $celular }}" data-correop="{{ $correo_personal }}" data-correoi="{{ $correo_institucional }}" data-ine="{{ $ine }}" data-pasaporte="{{ $pasaporte }}" data-vencimientopas="{{ $vencimiento_pasaporte }}" data-swift="{{ $swift }}" data-iban="{{ $iban }}" data-inedocumento="{{ $ine_documento }}" data-pasaportedocumento="{{ $pasaporte_documento }}" data-comprobantedomicilio="{{ $comprobante_domicilio }}" data-lpoadocumento="{{ $lpoa_documento }}" data-formapertura="{{ $formulario_apertura }}" data-formriesgos="{{ $formulario_riesgos }}" data-tarjeta="{{ $tarjeta }}" data-identificador="{{ $identificador_mam }}" type="button" title="Editar cliente" class="btn btn-success btn-sm btn-icon edit" id="edit"> <i class="bi bi-pencil"></i></a>
    <a href="" data-id="{{ $id }}" data-nombre="{{ $nombre }}" data-apellidop="{{ $apellido_p }}" data-apellidom="{{ $apellido_m }}" data-fechanac="{{ $fecha_nac }}" type="button" title="Imprimir LPOA" class="imprimirLPOAButton btn btn-dark btn-sm btn-icon print d-none"> <i class="bi bi-file-earmark-pdf-fill"></i></a>
@else
    Sin acciones
@endif